version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - net
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    networks:
      - net

  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    command: poetry run python main.py --run api
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - src/.env.dev
    networks:
      - net
    depends_on:
      - migrate
  migrate:
    build:
      context: .
      dockerfile: src/Dockerfile
    command: poetry run alembic upgrade head
    env_file:
      - src/.env.dev
    depends_on:
      - postgres
    networks:
      - net
  worker:
    build:
      context: .
      dockerfile: src/Dockerfile
    command: poetry run python main.py --run worker
    container_name: worker
    env_file:
      - src/.env.dev
    depends_on:
      - api
    networks:
      - net
  notification:
    build:
      context: .
      dockerfile: src/Dockerfile
    command: poetry run python main.py --run notification
    container_name: notification
    env_file:
      - src/.env.dev
    depends_on:
      - api
    networks:
      - net

volumes:
  pgdata:
    driver: local
networks:
  net:
    name: "net"
    #external: true

